name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Lint with ESLint
        run: npx eslint .

      - name: Format with Prettier
        run: npx prettier --write .

      - name: Test with Jest
        run: npx jest
      