name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  docker:
    runs-on: [self-hosted]
    steps:
      -
        name: Checkout Repository
        uses: actions/checkout@v2
      -      
        name: Build 
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: shanthosh04/Veranstaltungskalender_App:latest